zendesk/iron_bank

- .reek
- lib/iron_bank.rb
- lib/iron_bank/open_tracing.rb
- spec/iron_bank/open_tracing_spec.rb
This changeset removes the `Datadog#configure` block from `lib/iron_bank.rb` and instead adds the `service_name` as an option for `ddtrace` middleware ([reference](https://github.com/DataDog/dd-trace-rb/blob/edd3d553177b1ee89517cbdcb30e8cb4a79d88af/lib/ddtrace/contrib/faraday/middleware.rb#L57)).
> remove Datadog#configure call from library initializer

- lib/iron_bank/action.rb
- lib/iron_bank/error.rb
- spec/iron_bank/action_spec.rb
Add `IronBank::UnprocessableEntity` exception
It will raise the error when one of the following condition matches:
- When the response code is `422`
- When the action call returns `Success` body value as `false`
Zuora doesn't return `422` in general, but it returns the `Success` body value as `false`
**Low**
> Add `IronBank::UnprocessableEntity` exception

- .reek
- lib/iron_bank.rb
- lib/iron_bank/client.rb
- lib/iron_bank/faraday_middleware.rb
- lib/iron_bank/faraday_middleware/raise_error.rb
- lib/iron_bank/faraday_middleware/retriable_auth.rb
- spec/iron_bank/faraday_middleware/retriable_auth_spec.rb
Renew auth token on 401
**When the response is 401:**
- Auto-renew auth token and update request header
- Retry the requests once more
**Additional changes:**
- Create retriable_auth middleware plug/unplug easily
- Move Faraday middlewares into its own folder
- Register middlewares
> Renew auth token on 401

- lib/iron_bank/client.rb
- lib/iron_bank/error.rb
- lib/iron_bank/faraday_middleware/retriable_auth.rb
- spec/iron_bank/faraday_middleware/retriable_auth_spec.rb
Update retry condition to support older versions of `Faraday`
- Retry status introduced with `Faraday` >= 0.15.0
- Add `IronBank::Unauthorized` error
- Retry on `IronBank::Unauthorized`
Extra information (technical references, etc.) that you would like the reviewers
to be aware of.
Low
To support older versions of Faraday
> Update retry condition to support older versions of Faraday

- .travis.yml
- iron_bank.gemspec
This changeset removes Ruby `2.2.x` as a supported version, as well as clean up the Travis file to only tests all three supported Ruby version.
**Medium.** Remove unsupported Ruby version, enforce minimum Ruby version to `2.3` it in `gemspec` file.
> remove Ruby 2.2.x as a supported version

- lib/iron_bank/associations.rb
- lib/iron_bank/resources/invoice.rb
- lib/iron_bank/resources/product.rb
- lib/iron_bank/resources/product_rate_plan.rb
- lib/iron_bank/resources/product_rate_plan_charge.rb
- lib/iron_bank/resources/product_rate_plan_charge_tier.rb
- lib/iron_bank/resources/rate_plan.rb
- lib/iron_bank/resources/rate_plan_charge.rb
- lib/iron_bank/resources/rate_plan_charge_tier.rb
- lib/iron_bank/resources/subscription.rb
- spec/shared_examples/associations.rb
This changeset renames the `:aka` (also known as) option when defining an association for `:alias` which is much clearer in the code (as proven by removing the comment explaining what `aka` stands for).
**Low.** Internal option only, not publicly exposed (unless someone is defining a custom Zuora model, which I think is not usual).
> Rename :aka option to :alias when defining an association

- lib/iron_bank/object.rb
Refactors the `IronBank::Object` class:
* Extracts the camelizing/underscoring into lambdas, obviating the need for
separate `#camelize_<type>` & `#underscore_<type>` methods
* Reworks the type-checking to support array payloads!
Internal refactor; no version bump required
**Low**: Internal refactor with good unit specs.
> Refactors `IronBank::Object`

- lib/iron_bank/action.rb
- lib/iron_bank/actions/amend.rb
- lib/iron_bank/actions/create.rb
- lib/iron_bank/actions/delete.rb
- lib/iron_bank/actions/execute.rb
- lib/iron_bank/actions/generate.rb
- lib/iron_bank/actions/query.rb
- lib/iron_bank/actions/query_more.rb
- lib/iron_bank/actions/subscribe.rb
- lib/iron_bank/actions/update.rb
- spec/iron_bank/action_spec.rb
- spec/iron_bank/actions/amend_spec.rb
- spec/iron_bank/actions/create_spec.rb
- spec/iron_bank/actions/delete_spec.rb
- spec/iron_bank/actions/execute_spec.rb
- spec/iron_bank/actions/generate_spec.rb
- spec/iron_bank/actions/query_more_spec.rb
- spec/iron_bank/actions/query_spec.rb
- spec/iron_bank/actions/subscribe_spec.rb
- spec/iron_bank/actions/update_spec.rb
- spec/shared_examples/action.rb
Reworks the `IronBank::Action` classes to accept & return underscored hashes
(handling the camel-case conversion transparently to the caller.)
Likely requires a major version bump, as the responses for all actions have
been changed (underscored.)
**High:** Reworks the args & returned values for all actions.
> Reworks `IronBank::Action` Arguments & Responses

- .reek.yml
- lib/iron_bank/local.rb
- lib/iron_bank/local_records.rb
@mickaelpham @rringler 
the ruby build in symbol header convert will strip the underscore from header:  https://github.com/ruby/ruby/blob/ruby_2_3/lib/csv.rb#L985-L987
we only want to convert the string to symbol
**Low**
> header converter

- .reek.yml
- iron_bank.gemspec
- lib/iron_bank.rb
- lib/iron_bank/action.rb
- lib/iron_bank/client.rb
- lib/iron_bank/error.rb
- lib/iron_bank/faraday_middleware.rb
- lib/iron_bank/faraday_middleware/raise_error.rb
- lib/iron_bank/faraday_middleware/renew_auth.rb
- lib/iron_bank/queryable.rb
- spec/iron_bank/action_spec.rb
- spec/iron_bank/error_spec.rb
- spec/iron_bank/faraday_middleware/renew_auth_spec.rb
- spec/shared_examples/queryable.rb
Updates `IronBankError.from_response` to inspect the response body, as many of
Zuora's errors are return with a 200 status code, and are indicated in the body.
**Low**: Adds additional specificity to error-handling.
> Updates `IronBank::Error.from_response` To Inspect the Response Body

- .reek.yml
- lib/iron_bank/client.rb
- lib/iron_bank/configuration.rb
Updates `IronBank::Client` to fetch its retry options from
`IronBank::Configuration`. This will allow clients to be able to customize how
their requests are retried.
**Low**: Adds flexibility to how the retry options are sourced.
* _Rollback:_ Revert commit
> Updates `IronBank::Client` to Fetch Retry Options From Configuration

- Gemfile.lock
- README.md
- lib/iron_bank/describe/object.rb
- lib/iron_bank/local_records.rb
- lib/iron_bank/version.rb
- spec/iron_bank/local_records_spec.rb
- Updated `BACKOFF` constant to be simpler and have up to 10 attempts since `ProductRatePlanChargeTier` data source can prove very long to execute.
- Added known issue in `README.md` about it and how to recover from it.
**Low.** Task is only used during setup time.
> Log statements and updated backoff strategy for local records export

- lib/iron_bank/resources/invoice.rb
- spec/iron_bank/resources/invoice_spec.rb
We changed how the `#reload` method works. It now returns the instance of the reloaded resource and not the updated `remote` hash. This introduced a bug with `IronBank::Invoice#body` which calls `#reload` if the `body` is missing (since it cannot be queried using ZOQL when there are more than one invoice in the response).
**Low.** Fix a bug where invoice body is not returned.
> Fix IronBank::Invoice#body method

- Gemfile.lock
- lib/iron_bank/resources/product_rate_plan_charge_tier.rb
- lib/iron_bank/version.rb
- spec/iron_bank/resources/product_rate_plan_charge_tier_spec.rb
Add the following `exclude_fields` to `ProductRatePlanChargeTier` to allow it to be live-queried (when the local records are not present).
```
Active
IncludedUnits
OveragePrice
DiscountAmount
DiscountPercentage
```
Caveat: this doesn't let us live-query Discount-Amount or Discount-Percentage tiers, but that's also a limitation of Zuora query. This should not be an issue though if the `LocalRecords` are properly exported using Zuora Export ZOQL (which doesn't have the same kind of limitation).
**Low.** In their current state, `ProductRatePlanChargeTier` are not queryable.
> Allow ProductRatePlanChargeTiers to be live-queried

- lib/iron_bank/resources/taxation_item.rb
- spec/iron_bank/resources/taxation_item_spec.rb
TSIA
**Low.** Fields are only available through a ZOQL export.
> Exclude CreditAmount and PaymentAmount from query fields

- lib/iron_bank.rb
- lib/iron_bank/payment_run.rb
- spec/iron_bank/payment_run_spec.rb
- Add the ability to create a payment run for a given Zuora account.
Note that we are using the _commerce_ REST APIs, so the endpoint is `v1/payment-runs`, hence it's not an `Operation`, nor it is an `Action`. This is why we directly nested the class under `IronBank` module.
- https://www.zuora.com/developer/api-reference/#operation/POST_PaymentRun
**Low.** Brand new operation available through Iron Bank.
> Add PaymentRun#create

- lib/iron_bank/actions/query.rb
- spec/iron_bank/actions/query_spec.rb
- spec/shared_examples/action.rb
The [`Query`](https://www.zuora.com/developer/api-reference/#operation/Action_POSTquery) action from Zuora accepts an optional `batchSize` parameter (nested in a `conf` object).
> Defines the batch size of the query result. The range is 1 - 2000 (inclusive). If a value higher than 2000 is submitted, only 2000 results are returned.
This changeset modifies the `IronBank::Query.call` method to accept an `limit` option.
```rb
IronBank::Query.call "select Id, Name from Product", limit: 1
```
**Existing calls are unchanged** as we are defaulting `limit` to `0` and not passing it to Zuora if `limit.zero?` is `TRUE`.
```rb
IronBank::Query.call "select Id, Name from Product"
```
**Low.** New optional parameter, doesn't affect existing calls.
> Add limit (optional) parameter to Query call

- lib/iron_bank/csv.rb
- spec/iron_bank/csv_spec.rb
Updates the `IronBank::CSV` `:decimal_integer` & `:decimal_float` converters to 
handle null fields. Ruby 2.5 has changed the CSV parsing behavior such that it 
sometimes passes a `nil` argument to the converters.
It also removes the exception rescuing behavior, which will surface errors in 
the conversion more quickly.
**Low**: Adds an additional nil-check.
* _Rollback:_ Revert commit
> Updates `IronBank::CSV` Converters

- Gemfile.lock
Bumps the `nokogiri` gem to address a CVE.
* https://nvd.nist.gov/vuln/detail/CVE-2019-5477
**Low**: Bumps a gem dependency.
* _Rollback:_ Revert commit
> Bumps Nokogiri Gem

- lib/iron_bank/actions/query.rb
- lib/iron_bank/cacheable.rb
- lib/iron_bank/local.rb
- lib/iron_bank/queryable.rb
- spec/shared_examples/cacheable.rb
- spec/shared_examples/local.rb
- spec/shared_examples/queryable.rb
Zuora let us specify a `limit` parameter when making a `Query`. By leveraging this, we can offer an "efficient" (well, as fast as Zuora response) way of querying the first record (usually, this is sorted by Zuora in `last_modified_at DESC` order).
There are many uses, but my preferred one is to quickly test a `ZOQL` query, which you can see in https://github.com/zendesk/iron_bank/pull/38
```rb
IronBank::Account.first
```
**Low.** Brand new class method, not used anywhere. Minor bump needed (add new feature).
> Add a #first method for each queryable resource

- lib/iron_bank/describe/excluded_fields.rb
- spec/iron_bank/describe/excluded_fields_spec.rb
Use `where(id: "XYZ")` instead of `first`, making that call to Zuora (when successful) a lot faster, since `id` is an indexed field. The previous use of `#first` and the subsequent `limit: 1` passed to Zuora was timing out (HTTP requests) on a large production Zuora tenant.
**Low.** Small change to the `ExcludedFields` service class. Does not affect runtime.
> Faster query when checking fields

- lib/iron_bank/describe/excluded_fields.rb
- lib/iron_bank/metadata.rb
- lib/iron_bank/resources/invoice.rb
- lib/iron_bank/resources/product_rate_plan.rb
- lib/iron_bank/resources/rate_plan_charge.rb
- spec/shared_examples/metadata.rb
Fix an issue when running `bundle exec rake excluded_fields` where the `IronBank::Schema#excluded_fields` would not include fields from the current configuration file, effectively stomping on them.
Execute this command twice:
```
bundle exec rake excluded_fields
```
And on the second run, the fields are effectively removed from the `excluded_fields.yml` file, which is not the expected behavior.
Running the rake task should be idempotent.
**Low.** Bug fix for `rake` task.
> Append excluded fields to the schema instead of stomping on it

- lib/iron_bank/metadata.rb
- lib/iron_bank/schema.rb
- spec/iron_bank/configuration_spec.rb
- spec/iron_bank/schema_spec.rb
- spec/shared_examples/metadata.rb
Modifies the `IronBank::Schema#reset` method to re-read the XML files (from the exported schema) and handle any new fields added to it without having to reload the entire class.
When running `IronBank::Schema.export`, new fields could be present in the exported files. But these fields are not available as an instance method and/or query fields for each `IronBank::Resources` since the `#with_schema` has not been called again for these class.
1. Edit your `Account.xml` (or any other class) to remove a `<field>...</field>` XML node
2. Open an IronBank console by running `bin/console`
3. Verify that your `IronBank::Account` no longer define a method associated with that field
```rb
IronBank::Account.instance_methods.include?(:my_field__c)
```
4. **Without quitting** the `bin/console`, edit …
> IronBank::Schema#reset should completely refresh each resource

- spec/iron_bank/authentications/cookie_spec.rb
- spec/iron_bank/authentications/token_spec.rb
- spec/iron_bank/client_spec.rb
- spec/shared_examples/faraday_connection.rb
- Add coverage for `Faraday::Connection` configuration block
- Add coverage for default `retry_if` proc
_Drop mic_
**Low.** Improve spec coverage, no change to existing code.
> Improve spec coverage (100%)

- Rakefile
- lib/iron_bank/describe/excluded_fields.rb
- spec/iron_bank/describe/excluded_fields_spec.rb
Updates `IronBank::Describe::ExcludedFields` & the `:excluded_fields` rake task
such that the excluded fields are sorted when saved to a file.
**EDIT**
It allows us to have better `git diff` since this file is (generally) expected to be versioned.
**Low**: Updates the sorting of an exported file.
* _Rollback:_ Revert commit
> Sorts the Excluded Fields for Resources

- .env.example
- .gitignore
- .reek.yml
- bin/console
- lib/iron_bank.rb
- lib/iron_bank/configuration.rb
- lib/iron_bank/user.rb
- spec/fixtures/zuora_users.csv
- spec/iron_bank/user_spec.rb
Zuora returns `UpdatedById` for most of its resources. This corresponds to the Zuora user ID who last modified that resource. Unfortunately, Zuora does not offer an API for you to query the users in your Zuora tenant.
The [Zuora Knowledge Center](https://knowledgecenter.zuora.com/CF_Users_and_Administrators/A_Administrator_Settings/Manage_Users#Export_User_Data_to_a_CSV_File) does reference a way to export all users in your tenant. We leverage this report through IronBank to let your provide the CSV as a configuration option (`zuora_users_file`).
This make your users available through the `IronBank::User` class.
```rb
IronBank::User.all
user = IronBank::User.find(user_id)
user.user_name
user.last_login
```
**Low.** Net new feature.
> Add IronBank::User

- lib/iron_bank/resources/rate_plan_charge.rb
- spec/iron_bank/resources/rate_plan_charge_spec.rb
`Price` is not a query-able field when the `RatePlanCharge` has a pricing model of:
- Tiered
- Volume
- Discount-Fixed Amount
- Discount Percentage
It was only available for:
- Flat Fee
- Per Unit
And only through the ZOQL query. Zuora does not even add the `:price` attribute in their API response for their [CRUD: Get rate plan charge](https://www.zuora.com/developer/api-reference/#operation/Object_GETRatePlanCharge) operation.
Hence, we are deprecating `IronBank::Charge#price` method and will be removing it in future versions.
Users should be using the `#tiers` method for a given `RatePlanCharge` to find out the price information they are looking for.
**Low.** Deprecate a method that was not returning the proper response for any pricing model other than "Flat Fee" and "Per Unit."
> Exclude #price field from RatePlanCharge query

- lib/iron_bank/collection.rb
- spec/iron_bank/collection_spec.rb
I found that it would be helpful to use the `.empty?` method on a `Collection`.  I've delegated this method to `@records`, following the pattern of other method delegations in this class.
**Low**
> Delegate empty? to records for Collection

- lib/iron_bank/endpoint.rb
- spec/iron_bank/endpoint_spec.rb
This change adds support in `IronBank::Endpoint#base_url` to accommodate name variation for the `"services"` subdomain for when it might be prefixed with the word `"rest"` (eg: `"restservices999.zuora.com"`)
The new tenant being stood up to replace `services559` is setup to receive request at `restservices058`
**Low.** Updates validation in `IronBank::Endpoint#base_url` to allow for the `"rest"` prefix (eg: `restservices123` vs `services123`)
> Support prefixed variation of "services" hostname.

- lib/iron_bank/local.rb
- spec/iron_bank/local_spec.rb
The `Queryable` module allows querying multiple ids in one query,
however `LocalRecord` module does not,
so if I query with multiple IDs, cached local records will be ignored.
This PR bring feature parity to local records.
Extra information (technical references, etc.) that you would like the reviewers
to be aware of.
Medium
> Allow LocalRecord `where` to accept array of values

- lib/iron_bank/describe/excluded_fields.rb
Fixes #63 
This list is generated by querying Zuora with all fields, and removing
the faulty fields, one by one, until the query succeeds.
Until recently, Zuora was returning HTTP 500 Internal Server Error when
a non-queryable field was passed in the query. It now returns HTTP 400
Bad Request Error, but this exception was not rescued in the service
class generating the list of excluded fields.
**Low** since it's broken with the current Zuora release.
> fix: excluded fields

- .github/CODEOWNERS
**None**. Ownership update only (broader Zendesk team).
> chore: change ownership to all of zendesk/billing

- lib/iron_bank/endpoint.rb
- spec/iron_bank/endpoint_spec.rb
Update the regex to reflect the new zuora instance url in staging `rest.test.zuora.com`.
Jira: https://zendesk.atlassian.net/browse/WALR-5898
**Medium**: It may break connection to staging.
> Update regex for staging zuora

- lib/iron_bank/describe/object.rb
- lib/iron_bank/metadata.rb
- spec/fixtures/objects/account.xml
- spec/iron_bank/describe/object_spec.rb
- spec/shared_examples/metadata.rb
* Add support to query custom fields for resources
* returns an array of all selectable custom fields
Usage: 
```
IronBank::Account.query_custom_fields 
[ "MyCustomField__c_1", "MyCustomField__c_2" ... ]
```
**Medium** 
* adds support to query selectable custom fields, shouldn't break any existing features
> Add support to query custom fields for resource objects

- .reek.yml
- lib/iron_bank/client.rb
- lib/iron_bank/configuration.rb
Default Iron Bank to use Zuora at version 211.0 This PR is being blocked by [Update Env](https://github.com/zendesk/iron_bank/pull/86)
- JIRA ticket: [OTTR-1206](https://zendesk.atlassian.net/browse/OTTR-1206)
Medium - Configuration on Iron Bank might effect all clients.
> [OTTR-1206] Default IronBank to use the Zuora minor version 211.0

- lib/iron_bank/collection.rb
- spec/iron_bank/collection_spec.rb
This change-set implements `IronBank::Collection#to_ary` as a way to support implicit array conversions in Ruby. 
IronBank::Collection is not an array, but it tries to mimic acting like one. In some instances, this results in it not quite working where one would expect.
This  allows things like the below to work:
```ruby
a, b, c = some_iron_bank_collection
account = IronBank::Account.find(...)
rate_plans = account.subscriptions.flat_map(&:rate_plans)
```
Prior to this change anything that relied on impilcit conversion returned an IronBank::Collection which led to some strange results. 
Running the below code for an account  with multiple subscriptions:
```ruby
account = IronBank::Account.find(...)
s1, s2 = account.subscriptions
```
Before this change-set `s1` was assigned to the whole …
> IronBank::Collection has learned #to_ary in order to support implicit array conversions

- Gemfile.lock
This [snyk security vulnerability](https://app.snyk.io/org/growth-and-monetization/project/32542bd6-870c-495b-b68d-82c1f8f4d697/pr-check/4213318d-5b46-46ff-86e0-99797d4bea0d) for [CVE-2022-23476](https://www.cve.org/CVERecord?id=CVE-2022-23476) indicates we need to bump nokogiri to 1.13.10. 
From Snyk: 
> [nokogiri](https://nokogiri.org/) is a gem for parsing HTML, XML, SAX, and Reader.
>
> Affected versions of this package are vulnerable to Unchecked Return Value due to failing to check the return value from xmlTextReaderExpand in the method Nokogiri::XML::Reader#attribute_hash. Exploiting this vulnerability can lead to a null pointer exception when parsing invalid markup.
- [BILL-16296](https://zendesk.atlassian.net/browse/BILL-16296)
**Medium** bumps nokogiri gem
> [BILL-16296] Bump nokogiri to 1.13.10 due to CVE-2022-23476

- .github/workflows/ruby-gem-publication
This adds a new workflow to publish new versions of the IronBank gem to RubyGems.org without needing permissions to do so manually.
Reference - https://github.com/zendesk/gw/blob/d01a1fa90248f834bc73ed8244895746654c88e1/ruby-gem-publication/README.md
**Medium** changes to GH CI to publish new gems.
> Adding basic workflow to publish released gems

- Gemfile.lock
- `bundle update --conservative activesupport`
Snyk issue: https://app.snyk.io/org/growth-and-monetization/project/b6817ceb-01d3-41fa-889b-ec04a1fd6fb4#issue-SNYK-RUBY-ACTIVESUPPORT-5851458
Need to update ActiveSupport gem before the vulnerability goes outside of SLA.
Fix: bundle update --conservative activesupport
JIRA: https://zendesk.atlassian.net/browse/BILL-19467
**Low**: Gem Bump
> [BILL-19467] Update activesupport to fix CVE

- Gemfile.lock
- iron_bank.gemspec
- lib/iron_bank.rb
- lib/iron_bank/faraday_middleware/response/raise_error.rb
- lib/iron_bank/faraday_middleware/response/renew_auth.rb
Updates faraday to 2.x
Gem diff: https://github.com/lostisland/faraday/compare/v1.10.3...v2.12.0
Medium: Major version bump to faraday which contains breaking changes
> Update faraday to 2.x
